### ISSUE TITLE
getting error while selecting the board

### ISSUE THREAD

**Issue by khansaad1275** [hevalhazalkurt/PinPy#1]
Please Tell me what should i do

C:\Users\12345\PycharmProjects\python games\venv\Scripts\python.exe" F:/new/PinPy-master/pin.py
Traceback (most recent call last):
  File "F:/new/PinPy-master/pin.py", line 181, in <module>
    pin()
  File "F:/new/PinPy-master/pin.py", line 161, in pin
    driver.find_element_by_xpath(board).click()
  File "C:\Users\12345\PycharmProjects\python games\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\12345\PycharmProjects\python games\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\12345\PycharmProjects\python games\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\12345\PycharmProjects\python games\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string
  (Session info: chrome=79.0.3945.130)

![image](https://user-images.githubusercontent.com/32749921/73760551-7fe99300-4793-11ea-9761-6caddf5a1e50.png)

the X variable is not used

**Comment by hevalhazalkurt** [comment]
Sometimes the program needs some slicing operations depends on your product name and board name.  Can you give me a screenshot from your board name (board_data dictionary) and your image name?

**Comment by Archy83** [comment]
I have the same problem

**Comment by hevalhazalkurt** [comment]
> I have the same problem

I checked, the source code works well but it could be a problem because of your board or image name. Can you give me a screenshot from your board name (board_data dictionary) and your image name?

**Comment by irosadie** [comment]
i have same issue
# Select board
driver.find_element_by_xpath(board).click() // the board params from where??
time.sleep(2)

**Comment by hevalhazalkurt** [comment]
> i have same issue
> 
> # Select board
> driver.find_element_by_xpath(board).click() // the board params from where??
> time.sleep(2)

Hello @irosadie the program define `board` from `pre_board()` function. If you can't set up your `board_data` dictionary correctly it won't work. Please make sure your image names and `board_data` set up correctly, and read [defining board](https://github.com/hevalhazalkurt/PinPy#define-your-pinterest-board-details) section on documentation for more detail and example.
